% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 18-Jun-2020 12:22:32
%
% This script assumes these variables are defined:
%
%   dataset_som_fdk6 - input data.
clc; clear all; close all; 
load('dataset_som_fdk6_t2.mat')
x = dataset_som_fdk6;

% Create a Self-Organizing Map
dimension1 = 5;
dimension2 = 5;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net_t1,tr_1] = train(net,x);

% Test the Network
resultados_test1 = net(x);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
% figure, plotsomtop(net)
% figure, plotsomnc(net)
% figure, plotsomnd(net)
% figure, plotsomplanes(net)
figure, plotsomhits(net,x)
% figure, plotsompos(net,x)

%% Función para recolectar los valores clasificados 

